apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: tlc
    service: front
spec:
  selector:
    app: tlc
    service: front
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 9100
    name: node-exporter
