apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: tlc
    service: prometheus
spec:
  selector:
    matchLabels:
      app: tlc
      service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tlc
        service: prometheus
    spec:
      containers:
      - name: prometheus
        image: ubuntu/prometheus:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: prometheus-data-pv
            mountPath: /prometheus
          - name: prometheus-conf-pv
            mountPath: /etc/prometheus
            readOnly: true
      volumes:
        - name: prometheus-data-pv
          persistentVolumeClaim:
            claimName: prometheus-data-pv-claim
        - name: prometheus-conf-pv
          configMap:
            defaultMode: 420
            name: prometheus-conf

