apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: tlc
    service: db
spec:
  selector:
    matchLabels:
      app: tlc
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tlc
        service: db
    spec:
      containers:
      - name: db
        image: quentinlegot/tlc-db:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
          - name: db-data-pv
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_root_pass.txt
                name: database-creds
          - name: MYSQL_DATABASE
            value: tlc
          - name: MYSQL_USER
            value: tlc
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_pass.txt
                name: database-creds
      - name: node-exporter
        image: prom/node-exporter:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        args:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            mountPropagation: HostToContainer
            readOnly: true
          - name: sys
            mountPath: /host/sys
            mountPropagation: HostToContainer
            readOnly: true
      volumes:
        - name: db-data-pv
          persistentVolumeClaim:
            claimName: db-data-pv-claim
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc

