apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: tlc
    service: db
spec:
  selector:
    app: tlc
    service: db
  ports:
  - port: 3306
    name: db
  - port: 9100
    name: node-exporter
