apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tlc
resources:
  - front/front-deployment.yaml
  - front/front-svc.yaml
  - api/api-deployment.yaml
  - api/api-svc.yaml
  - db/db-deployment.yaml
  - db/db-svc.yaml
  - db/db-volume.yaml
  - etherpad/etherpad-deployment.yaml
  - etherpad/etherpad-svc.yaml
  - myadmin/myadmin-deployment.yaml
  - myadmin/myadmin-svc.yaml
  - mail/mail-deployment.yaml
  - mail/mail-svc.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/prometheus-svc.yaml
  - prometheus/prometheus-volume.yaml
  - grafana/grafana-deployment.yaml
  - grafana/grafana-svc.yaml
  - grafana/grafana-volume.yaml
  # - keycloak/keycloak-deployment.yaml
  # - keycloak/keycloak-svc.yaml
  - ingress.yaml
secretGenerator:
  - name: database-creds
    files:
      - db_pass.txt
      - db_root_pass.txt
configMapGenerator:
  - name: prometheus-conf
    files:
      - ./prometheus/prometheus.yml
  - name: etherpad-apikey
    files: 
      - ./api/APIKEY.txt
  - name: nginx-conf
    files:
      - ./front/app.conf