apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: tlc
    service: api
spec:
  selector:
    app: tlc
    service: api
  ports:
  - port: 8080
    name: api
  - port: 9100
    name: node-exporter