apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: tlc
    service: grafana
spec:
  selector:
    matchLabels:
      app: tlc
      service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tlc
        service: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: GF_SERVER_PROTOCOL
            value: http
          - name: GF_SERVER_DOMAIN
            value: quentinl.diverse-team.fr
          - name: GF_SERVER_ROOT_URL
            value: "%(protocol)s://%(domain)s:%(http_port)s/metrics"
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
        ports:
        - containerPort: 3000
          name: grafana3000
        volumeMounts:
          - name: grafana-data-pv
            mountPath: /var/lib/grafana
      - name: node-exporter
        image: prom/node-exporter:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
        args:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            mountPropagation: HostToContainer
            readOnly: true
          - name: sys
            mountPath: /host/sys
            mountPropagation: HostToContainer
            readOnly: true
      volumes:
        - name: grafana-data-pv
          persistentVolumeClaim:
            claimName: grafana-data-pv-claim
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
