apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: tlc
    service: grafana
spec:
  selector:
    app: tlc
    service: grafana
  ports:
  - port: 3000
    name: grafana
  - port: 9100
    name: node-exporter
