apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pv-claim
  labels:
    app: tlc
    service: grafana
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
