apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin
  labels:
    app: tlc
    service: myadmin
spec:
  selector:
    matchLabels:
      app: tlc
      service: myadmin
  template:
    metadata:
      labels:
        app: tlc
        service: myadmin
  strategy:
    type: Recreate
  spec:
    containers:
    - name: myadmin
      image: phpmyadmin:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      ports:
        - containerPort: 80
          name: myadmin80
      env:
        - name: PMA_HOST
          value: db
      
