apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin
  labels:
    app: tlc
    service: myadmin
spec:
  selector:
    matchLabels:
      app: tlc
      service: myadmin
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: tlc
        service: myadmin
    spec:
      containers:
      - name: myadmin
        image: phpmyadmin:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
            name: myadmin80
        env:
          - name: PMA_HOST
            value: db
      - name: node-exporter
        image: prom/node-exporter:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
        args:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            mountPropagation: HostToContainer
            readOnly: true
          - name: sys
            mountPath: /host/sys
            mountPropagation: HostToContainer
            readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc    
