apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad
  labels:
    app: tlc
    service: etherpad
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
