apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  labels:
    app: tlc
    service: etherpad
spec:
  selector:
    matchLabels:
      app: tlc
      service: etherpad
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: tlc
        service: etherpad
    spec:
      containers:
      - name: etherpad
        image: etherpad/etherpad:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: DB_TYPE
            value: mysql
          - name: DB_HOST
            value: db
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: tlc
          - name: DB_USER
            value: tlc
          - name: MINIFY
            value: "false"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: db_pass.txt
                name: database-creds
        volumeMounts:
          - name: etherpad-apikey-pv
            mountPath: /opt/etherpad-lite/APIKEY.txt
            readOnly: true
            subPath: APIKEY.txt
        ports:
        - containerPort: 9001
      - name: node-exporter
        image: prom/node-exporter:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
        args:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            mountPropagation: HostToContainer
            readOnly: true
          - name: sys
            mountPath: /host/sys
            mountPropagation: HostToContainer
            readOnly: true
      volumes:
        - name: etherpad-apikey-pv
          configMap:
            defaultMode: 420
            name: etherpad-apikey
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc

