apiVersion: v1
kind: Service
metadata:
  name: etherpad
  labels:
    app: tlc
    service: etherpad
spec:
  selector:
    app: tlc
    service: etherpad
  ports:
  - port: 9001
    name: etherpad
  - port: 9100
    name: node-exporter
